absl-py==1.4.0
astunparse==1.6.3
cachetools==5.3.0
charset-normalizer==3.1.0
click==8.1.3
cycler==0.11.0
dill==0.3.6
etils==0.9.0
flatbuffers==23.3.3
fonttools==4.38.0
gast==0.4.0
google-auth==2.17.3
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
googleapis-common-protos==1.59.0
grpcio==1.54.0
h5py==3.8.0
idna==3.4
imageio==2.28.1
importlib-metadata==6.6.0
importlib-resources==5.12.0
joblib==1.2.0
keras==2.11.0
kiwisolver==1.4.4
libclang==16.0.0
markdown==3.4.3
markupsafe==2.1.2
matplotlib==3.5.3
networkx==2.6.3
numpy==1.21.6
oauthlib==3.2.2
opencv-python==4.7.0
packaging==23.1
pandas==1.3.5
pillow==9.5.0
promise==2.3
protobuf==3.19.6
psutil==5.9.5
pydot==1.4.2
pyparsing==3.0.9
python-graphviz==0.20.1
pytz==2023.3
pywavelets==1.3.0
requests==2.29.0
requests-oauthlib==1.3.1
rsa==4.9
scikit-image==0.19.3
scikit-learn==1.0.2
scipy==1.7.3
tensorboard==2.11.2
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorflow==2.11.0
tensorflow-datasets==4.8.2
tensorflow-estimator==2.11.0
tensorflow-hub==0.13.0
tensorflow-metadata==1.12.0
termcolor==2.3.0
threadpoolctl==3.1.0
tifffile==2021.11.2
toml==0.10.2
torchvision==0.14.1
tqdm==4.65.0
typing-extensions==4.5.0
urllib3==1.26.15
werkzeug==2.2.3
wrapt==1.15.0
zipp==3.15.0

  - opencv-python==4.7.0
  - dm-tree==0.1.8
  - pyasn1==0.5.0
